---
title: "FigureB"
output: html_document
date: "2025-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

## Get Data

```{r data, echo=FALSE}
a_obs_dat <- read_csv("/Figures/data/all_mean.pi") %>% mutate(B_mean = pi_mean / 0.012) %>% mutate(Distance = start - 9950) %>% select(Distance, B_mean)
b_obs_dat <- read_csv("/Figures/data/40kb_gc_all_mean.pi")  %>% mutate(B_mean = pi_mean / 0.012) %>% mutate(Distance = start - 9950) %>% select(Distance, B_mean)
c_obs_dat <- read_csv("/Figures/data/40kb_f0.9_h0.5_all_mean.pi") %>% mutate(B_mean = pi_mean / 0.00631579) %>% mutate(Distance = start - 9950) %>% select(Distance, B_mean) # Needs / 0.00631579 instead of / 0.012
d_obs_dat <- read_csv("/Figures/data/OBS_Expand_5N_1T.csv") %>% mutate(pi_mean=pi) %>% select(start,pi_mean)  %>% mutate(B_mean = pi_mean / 0.012) %>% mutate(Distance = start - 9950) %>% select(Distance, B_mean)

WEAK_obs_dat <- read_csv("/revision_results/sim_results/rev_weakcontract_5N_1T_all.pi") %>% mutate(B_mean = pi / 0.003186913) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )
MOD_obs_dat <- read_csv("/revision_results/sim_results/rev_modcontract_5N_1T_all.pi") %>% mutate(B_mean = pi / 0.003186913) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )
GAMMA_obs_dat <- read_csv("/revision_results/sim_results/Bcalc_40kb_Dmelgamma_all.pi") %>% mutate(B_mean = pi / 0.012) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )
OBS_Contract_5N_1T <- read_csv("/sim_testing/demogsims/40kb_contract_5N_1T_all.pi") %>% mutate(B_mean = pi / 0.003186913) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )

neutral_contract_5N_2T <- read_csv("/revision_results/sim_results/Bcalc_40kb_neutral_contract_5N_2T_all.pi") %>% mutate(B_mean = pi / 0.012) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )

a_unc_dat <- read_csv("/Figures/data/nogcBasicParams.B")
b_unc_dat <- read_csv("/Figures/data/nogcBasicParams.B")
c_unc_dat <- read_csv("/Figures/data/nogcBasicParams.B")
d_unc_dat <- read_csv("/Figures/data/nogcBasicParams.B")


GAMMA_calc_dat <- read_csv("/revision_results/calc_results/GammaDfeParams.B")
WEAK_calc_dat <- read_csv("/revision_results/calc_results/ContractParams_5N_1T_WEAK.csv")
MOD_calc_dat <- read_csv("/revision_results/calc_results/ContractParams_5N_1T_MOD.csv")
expand_5N_2T_calc_dat <- ("")
bins_calc_dat <- read_csv("/sim_testing/demogsims/40kb_contract_5N_1T_all.pi")

EXP_Contract_5N_1T <- read_csv("/sim_testing/calculatedBfiles/40kb_contract_5N_1T.bvals")


a_calc_dat <- read_csv("/Figures/data/nogcBasicParams.B")
b_calc_dat <- read_csv("/Figures/data/gcBasicParams.B")
b_calc_dat <- read_csv("/Figures/data/gc_halfg.B")
c_calc_dat <- read_csv("/Figures/data/SelfParams_0.9S_0.5h.B")
d_calc_dat <- read_csv("/Figures/data/ExpandParams_5N_1T.B")


OBS_EARLY <- read_csv("/revision_results/sim_results/1N_earlyBcalc_40kb_contract_5N_2T_all.pi") %>% mutate(B_mean = pi / 0.012) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )

library(tidyverse)

obs_raw <- read_csv("/revision_results/sim_results/1N_earlyBcalc_40kb_contract_5N_2T_all.pi") %>%
  mutate(
    B = pi / 0.012,
    Distance = start - 9950,
    group = "obs"
  )%>%
  distinct(replicate, start, .keep_all = TRUE) # Dedup


exp_raw <- read_csv("/sim_testing/all.pi") %>%
  mutate(
    B = pi / 0.012,
    Distance = start - 9950,
    group = "exp"
  )
obs_summary <- obs_raw %>%
  group_by(Distance) %>%
  summarise(
    mean_B = mean(B),
    var_B = var(B),
    sd_B = sd(B),
    n = n(),
    se_B = sd_B / sqrt(n),
    .groups = "drop"
  )

exp_summary <- exp_raw %>%
  group_by(Distance) %>%
  summarise(
    mean_B = mean(B),
    var_B = var(B),
    sd_B = sd(B),
    n = n(),
    se_B = sd_B / sqrt(n),
    .groups = "drop"
  )

comparison <- inner_join(
  obs_summary,
  exp_summary,
  by = "Distance",
  suffix = c("_obs", "_exp")
)


burnin_plot <- ggplot(comparison) +
  geom_point(aes(Distance, mean_B_obs, colour = "13N")) +
  geom_point(aes(Distance, mean_B_exp, colour = "14N")) +
  labs(y = "B", colour = "Burn-in", x = "Distance from 10 kb selected element") +
  theme_minimal()
sqrt(mean((comparison$mean_B_obs - comparison$mean_B_exp)^2))

comparison$resid <- comparison$mean_B_obs - comparison$mean_B_exp

burnin_resid_plot<- ggplot(comparison, aes(Distance, resid)) +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_line() +
  theme_bw() +
  ylab("ΔB (13N - 14N)")

ggsave("/revision_results/figures/burnin_plot.pdf", burnin_plot, device = "pdf", dpi = 200, height = 6 * (5.2/8), width = 5.2, units = "in")
ggsave("/revision_results/figures/burnin_residplot.pdf", burnin_resid_plot, device = "pdf", dpi = 200, height = 3 * (5.2/8), width = 5.2, units = "in")

# 
# comparison <- comparison %>%
#   mutate(diff_mean = mean_B_obs - mean_B_exp)
# 
# ggplot(comparison) +
#   geom_hline(yintercept = 0, linetype = 2) +
#   geom_line(aes(Distance, diff_mean)) +
#   theme_bw() +
#   ylab("Observed - Expected mean B")
# 
# 
# comparison <- comparison %>%
#   mutate(
#     se_diff = sqrt(se_B_obs^2 + se_B_exp^2),
#     lower = diff_mean - 1.96 * se_diff,
#     upper = diff_mean + 1.96 * se_diff
#   )
# ggplot(comparison, aes(Distance, diff_mean)) +
#   geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +
#   geom_line() +
#   geom_hline(yintercept = 0, linetype = 2) +
#   theme_bw()
# 
# all_dat <- bind_rows(obs_raw, exp_raw)
# 
# t.test(B ~ group, data = all_dat)
# 
# 
# OBS_EARLY
# a_obs_dat
```

## Generate Figure

```{r Figure}

b_obs_dat
b_unc_dat
b_calc_dat

figa <- ggplot() +
  # model (uncorrected / baseline) as a soft gray line (optional)
  geom_line(data = a_unc_dat, aes(Distance, B), color = "grey30", linewidth = 1.6) +
  
  # model (your calc) as the primary blue line
  geom_line(data = a_calc_dat, aes(Distance, B), color = "blue", linewidth = 1.6) +
  
  # observations as points
  geom_point(data = a_obs_dat, aes(Distance, B_mean),
             color = "darkorange", size = 1.8, alpha = 0.7) +

  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  ) +
  scale_x_continuous(
  limits = c(0, 20200),
  breaks  = seq(0, 20000, by = 10000),
  expand  = c(0, 0)) +
  scale_y_continuous(
  limits = c(0.8,1),
  breaks  = seq(0.8, 1, by = 0.05),
  expand = c(0.01, 0)) +
  ylab("B") +
  theme(axis.title.x = element_blank()) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
  #xlab("Distance from 10 kb conserved element (bp)")

figb <- ggplot() +
  # model (uncorrected / baseline) as a soft gray line (optional)
  geom_line(data = b_unc_dat, aes(Distance, B), color = "grey30", linewidth = 1.6) +
  
  # model (your calc) as the primary blue line
  geom_line(data = b_calc_dat, aes(Distance, B), color = "blue", linewidth = 1.6) +
  
  # observations as points
  geom_point(data = b_obs_dat, aes(Distance, B_mean),
             color = "darkorange", size = 1.8, alpha = 0.7) +

  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  ) +
  scale_x_continuous(
  limits = c(0, 20200),
  breaks  = seq(0, 20000, by = 10000),
  expand  = c(0, 0)) +
  scale_y_continuous(
  limits = c(0.8,1),
  breaks  = seq(0.8, 1, by = 0.05),
  expand = c(0.01, 0)) +
  ylab("B") +
  theme(axis.title.x = element_blank()) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
  #xlab("Distance from 10 kb conserved element (bp)")

figd <- ggplot() +
  # model (uncorrected / baseline) as a soft gray line (optional)
  geom_line(data = d_unc_dat, aes(Distance, B), color = "grey30", linewidth = 1.6) +
  
  # model (your calc) as the primary blue line
  geom_line(data = d_calc_dat, aes(Distance, B), color = "blue", linewidth = 1.6) +
  
  # observations as points
  geom_point(data = d_obs_dat, aes(Distance, B_mean),
             color = "darkorange", size = 1.8, alpha = 0.7) +

  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  ) +
  scale_x_continuous(
  limits = c(0, 20200),
  breaks  = seq(0, 20000, by = 10000),
  expand  = c(0, 0)) +
  scale_y_continuous(
  limits = c(0.8,1),
  breaks  = seq(0.8, 1, by = 0.05),
  expand = c(0.01, 0)) +
  ylab("B") +
  xlab("Distance from 10 kb conserved element (bp)") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))

figc <- ggplot() +
  # model (uncorrected / baseline) as a soft gray line (optional)
  geom_line(data = c_unc_dat, aes(Distance, B), color = "grey30", linewidth = 1.6) +
  
  # model (your calc) as the primary blue line
  geom_line(data = c_calc_dat, aes(Distance, B), color = "blue", linewidth = 1.6) +
  
  # observations as points
  geom_point(data = c_obs_dat, aes(Distance, B_mean),
             color = "darkorange", size = 1.8, alpha = 0.6) +

  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  ) +
  scale_x_continuous(
  limits = c(0, 40200),
  breaks  = seq(0, 40000, by = 10000),
  expand  = c(0, 0)) +
  scale_y_continuous(
  limits = c(0.55,1),
  breaks  = seq(0.6, 1, by = 0.1),
  expand = c(0.01, 0)) +
  ylab("B") +
  xlab("Distance from 10 kb conserved element (bp)") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))


allfigB <- figa +
figb +
figd +
figc

ggsave("/Figures/allfigB2_newgc_preai.pdf", allfigB, device = "pdf", dpi = 600, height = 6 * (5.2/8), width = 5.2, units = "in")
```

```{r REVISIONS}
plot_no_unc_fig <- function(calc_dat, obs_dat){
  ggplot() +
  # model (uncorrected / baseline) as a soft gray line (optional)
  # geom_line(data = GAMMA_unc_dat, aes(Distance, B), color = "grey30", linewidth = 1.6) +
  
  # model (your calc) as the primary blue line
  geom_line(data = calc_dat, aes(Distance, B), color = "blue", linewidth = 1.6) +
  
  # observations as points
  geom_point(data = obs_dat, aes(Distance, B_mean),
             color = "darkorange", size = 1.8, alpha = 0.6) +

  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black")
  ) +
  scale_x_continuous(
  limits = c(0, 40200),
  breaks  = seq(0, 40000, by = 10000),
  expand  = c(0, 0)) +
  scale_y_continuous(
  limits = c(0.55,1),
  breaks  = seq(0.6, 1, by = 0.1),
  expand = c(0.01, 0)) +
  ylab("B") +
  xlab("Distance from 10 kb conserved element (bp)") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5))}

GAMMA <- plot_no_unc_fig(calc_dat = GAMMA_calc_dat, obs_dat = GAMMA_obs_dat)
WEAK <- plot_no_unc_fig(calc_dat = WEAK_calc_dat, obs_dat = WEAK_obs_dat)
MOD <- plot_no_unc_fig(calc_dat = MOD_calc_dat, obs_dat = MOD_obs_dat)
bins <- plot_no_unc_fig(calc_dat = bins_calc_dat, obs_dat = bins_calc_dat)
expand_5N_2T <- plot_no_unc_fig(calc_dat = expand_5N_2T_calc_dat, obs_dat = expand_5N_2T_obs_dat)
contract_5N_2T <- plot_no_unc_fig(calc_dat = contract_5N_2T_calc_dat, obs_dat = contract_5N_2T_obs_dat)

plot_no_unc_fig(calc_dat = EXP_Contract_5N_1T, obs_dat = OBS_Contract_5N_1T)

nOBS <- OBS_nContract_5N_1T %>% group_by(start) %>% summarise(navg = mean(pi, na.rm = TRUE)) %>% mutate(start = start - 10000)
mean(nOBS$navg)


figGAMMA
```

```{r TESTING}

DEMOGplotobsexp <- function(OBS, nOBS, EXP, cEXP, xlim = 40000, ylim = c(0.4,1.05)) {
  
  E2 <- EXP %>% mutate(bin = ceiling(Distance / 100)) %>% group_by(bin) %>% summarize(meanB = mean(B, na.rm = TRUE)) %>% mutate(start = bin*100 - 99)
  
  cE2 <- cEXP %>% mutate(bin = ceiling(Distance / 100)) %>% group_by(bin) %>% summarize(meanB = mean(B, na.rm = TRUE)) %>% mutate(start = bin*100 - 99)
  
  O2 <- OBS %>% group_by(start) %>% summarise(avg = mean(pi, na.rm = TRUE)) %>% mutate(start = start - 10000)
  
  nO2 <- nOBS %>% group_by(start) %>% summarise(navg = mean(pi, na.rm = TRUE)) %>% mutate(start = start - 10000)
  
  O3 <- nO2 %>% left_join(O2) %>% mutate(pipio = avg/mean(navg))
  
  
  ggplot(data = O3, aes(x = start, y = pipio)) + 
  geom_point(aes(color = "observed"), colour = "blue") +
  geom_line(data = E2, aes(x = start, y = meanB, colour = "expected"), colour = "red") +
  geom_line(data = cE2, aes(x = start, y = meanB, colour = "expected"), colour = "black") +
  xlim(0,xlim) +
  ylim(ylim) +
  theme_minimal() +
  ylab("B") +
  xlab("Distance from element (bp)")
}

WEAK_obs_dat <- read_csv("/revision_results/sim_results/rev_weakcontract_5N_1T_all.pi") %>% mutate(B_mean = pi / 0.003186913) %>%
  mutate(Distance = start - 9950) %>%
  group_by(Distance) %>%
  summarise(
    B_mean = mean(B_mean, na.rm = TRUE),
    .groups = "drop"
  )
WEAK_calc_dat <- read_csv("/revision_results/calc_results/ContractParams_5N_1T_WEAK.csv")

WEAK_calc_r <- WEAK_calc_dat %>% mutate(bin = ceiling(Distance / 100)) %>% group_by(bin) %>% summarize(meanB = mean(B, na.rm = TRUE)) %>% mutate(start = bin*100 - 99)
WEAK_obs_dat %>% mutate(start = Distance-49)
WEAK <- plot_no_unc_fig(calc_dat = , obs_dat = WEAK_obs_dat)
WEAK <- DEMOGplotobsexp(OBS = read_csv("/revision_results/sim_results/rev_weakcontract_5N_1T_all.pi"), nOBS = OBS_nContract_5N_1T, EXP = read_csv("/revision_results/calc_results/ContractParams_5N_1T_WEAK.csv"), cEXP = cEXP_Contract_5N_1T)
MOD <- DEMOGplotobsexp(OBS = read_csv("/revision_results/sim_results/rev_modcontract_5N_1T_all.pi"), nOBS = OBS_nContract_5N_1T, EXP = read_csv("/revision_results/calc_results/ContractParams_5N_1T_MOD.csv"), cEXP = cEXP_Contract_5N_1T)


contract_2T <- DEMOGplotobsexp(OBS = read_csv("/revision_results/sim_results/Bcalc_40kb_contract_5N_2T_all.pi"), nOBS = read_csv("/revision_results/sim_results/Bcalc_40kb_neutral_contract_5N_2T_all.pi"), EXP = read_csv("/revision_results/calc_results/ContractParams_5N_2T.csv"), cEXP = cEXP_Contract_5N_1T)

expand_2T <-  DEMOGplotobsexp(OBS = read_csv("/revision_results/sim_results/Bcalc_40kb_expand_5N_2T_all.pi"), nOBS = read_csv("/revision_results/sim_results/Bcalc_40kb_neutral_expand_5N_2T_all.pi"), EXP = read_csv("/revision_results/calc_results/ExpandParams_5N_2T.csv"), cEXP = cEXP_Contract_5N_1T)

OBS_Contract_5N_1T <- read_csv("/sim_testing/demogsims/40kb_contract_5N_1T_all.pi")
OBS_nContract_5N_1T <- read_csv("/sim_testing/demogsims/40kb_contract_neutral_5N_1T_all.pi")
EXP_Contract_5N_1T <- read_csv("/sim_testing/calculatedBfiles/40kb_contract_5N_1T.bvals")
cEXP_Contract_5N_1T <- read_csv("/sim_testing/calculatedBfiles/c40kb_contract_5N_1T.bvals")
DEMOGplotobsexp(OBS = OBS_Contract_5N_1T, nOBS = OBS_nContract_5N_1T, EXP = EXP_Contract_5N_1T, cEXP = cEXP_Contract_5N_1T)

# THE 2Ns = -100 CONTRACTION
# poetry run Bvalcalc --gene --params tests/testparams/ContractParams_5N_1T.py --plot /revision_results/sim_results/temp.png --pop_change --out /revision_results/sim_results/ContractParams_5N_1T_2Ns100.bvals --out_binsize 1 --constant_dfe
OBS100_Contract_5N_1T <- read_csv("/revision_results/sim_results/rev_100contract_5N_1T_all.pi")
OBS_nContract_5N_1T <- read_csv("/sim_testing/demogsims/40kb_contract_neutral_5N_1T_all.pi")
EXP_Contract_5N_1T <- read_csv("/revision_results/sim_results/ContractParams_5N_1T_2Ns100.bvals")
cEXP_Contract_5N_1T <- read_csv("/sim_testing/calculatedBfiles/c40kb_contract_5N_1T.bvals")
DEMOGplotobsexp(OBS = OBS100_Contract_5N_1T, nOBS = OBS_nContract_5N_1T, EXP = EXP_Contract_5N_1T, cEXP = cEXP_Contract_5N_1T)
```


```{r Recombination}
unc_r_dat <- read_csv("/revision_results/calc_results/rec.B")
calc_05_dat <- read_csv("/revision_results/calc_results/rec05.B")
calc_08_dat <- read_csv("/revision_results/calc_results/rec08.B")
calc_125_dat <- read_csv("/revision_results/calc_results/rec125.B")
calc_2_dat <- read_csv("/revision_results/calc_results/rec2.B")

# poetry run Bvalcalc --gene --params /BvalueCalculator/tests/testparams/nogcBasicParams.py  --out /revision_results/calc_results/rec.B --out_binsize 1

fig_r <- ggplot() +
  geom_line(data = unc_r_dat, aes(Distance, B, colour = "0.5 X E-8"), linewidth = 1.6) +
  geom_line(data = calc_05_dat, aes(Distance, B, colour = "0.25 X E-8"), linewidth = 1.6) +
  geom_line(data = calc_08_dat, aes(Distance, B, colour = "0.4 X E-8"), linewidth = 1.6) +
  geom_line(data = calc_125_dat, aes(Distance, B, colour = "0.625 X E-8"), linewidth = 1.6) +
  geom_line(data = calc_2_dat, aes(Distance, B, colour = "1 X E-8"), linewidth = 1.6) +
  scale_colour_manual(
    name = "Crossover rate (r)",
    values = c("0.5 X E-8" = "#2ca02c", "0.25 X E-8" = "#9467bd", "0.4 X E-8" = "#1f77b4",
               "0.625 X E-8" = "#ffa500", "1 X E-8" = "#ff4500")
  ) +
  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    legend.position = c(0.8, 0.5),
    legend.background = element_rect(fill = "white", colour = "black")
  ) +
  scale_x_continuous(limits = c(0, 20500), breaks = seq(0, 20000, by = 10000), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0.7, 1), breaks = seq(0.7, 1, by = 0.05), expand = c(0.01, 0)) +
  ylab("B") +
  theme(axis.title.x = element_blank()) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) +
  xlab("Distance from 10 kb conserved element (bp)")

fig_r
```

```{r Gamma DFE}
unc_g_dat <- read_csv("/revision_results/calc_results/g.B")
calc_g05g_dat <- read_csv("/revision_results/calc_results/g05g.B")
calc_g2g_dat <- read_csv("/revision_results/calc_results/g2g.B")
calc_g05s_dat <- read_csv("/revision_results/calc_results/g05s.B")
calc_g2s_dat <- read_csv("/revision_results/calc_results/g2s.B")

# poetry run Bvalcalc --gene --params /BvalueCalculator/tests/testparams/GammaDfeParams.py --out /revision_results/calc_results/g.B --out_binsize 1 --gamma_dfe

fig_g <- ggplot() +
  geom_line(data = unc_g_dat, aes(Distance, B, colour = "Uncorrected"), linewidth = 1.6) +
  geom_line(data = calc_g05g_dat, aes(Distance, B, colour = "0.5 X mean_2Ns"), linewidth = 1.6) +
  geom_line(data = calc_g2g_dat, aes(Distance, B, colour = "2 X mean_2Ns"), linewidth = 1.6) +
  geom_line(data = calc_g05s_dat, aes(Distance, B, colour = "0.5 X shape"), linewidth = 1.6) +
  geom_line(data = calc_g2s_dat, aes(Distance, B, colour = "2 X shape"), linewidth = 1.6) +
  scale_colour_manual(
    name = "DFE scaling",
    values = c("Uncorrected" = "#2ca02c", "0.5 X mean_2Ns" = "#1f77b4", "2 X mean_2Ns" = "#ffa500",
               "0.5 X shape" = "#ff4500", "2 X shape" = "#9467bd")
  ) +
  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    legend.position = c(0.8, 0.45),
    legend.background = element_rect(fill = "white", colour = "black")
  ) +
  scale_x_continuous(limits = c(0, 20500), breaks = seq(0, 20000, by = 10000), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0.82, 1), breaks = seq(0.7, 1, by = 0.05), expand = c(0.01, 0)) +
  ylab("B") +
  theme(axis.title.x = element_blank()) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) +
  xlab("Distance from 10 kb conserved element (bp)")

fig_g
```

```{r Selfing}
unc_f_dat <- read_csv("/revision_results/calc_results/f.B")
calc_f05_dat <- read_csv("/revision_results/calc_results/f05.B")
calc_f08_dat <- read_csv("/revision_results/calc_results/f08.B")
calc_f09_dat <- read_csv("/revision_results/calc_results/f09.B")
calc_f095_dat <- read_csv("/revision_results/calc_results/f095.B")
# calc_f2_dat <- read_csv("/revision_results/calc_results/f2.B")



fig_f <- ggplot() +
  geom_line(data = calc_f05_dat, aes(Distance, B, colour = "F = 0.5"), linewidth = 1.6) +
  geom_line(data = calc_f08_dat, aes(Distance, B, colour = "F = 0.8"), linewidth = 1.6) +
  geom_line(data = calc_f09_dat, aes(Distance, B, colour = "F = 0.9"), linewidth = 1.6) +
  geom_line(data = calc_f095_dat, aes(Distance, B, colour = "F = 0.95"), linewidth = 1.6) +
  scale_colour_manual(
    name = "Selfing rate",
    values = c("F = 0.5" = "#9467bd", "F = 0.8" = "#1f77b4",
               "F = 0.9" = "#2ca02c", "F = 0.95" = "red")
  ) +
  theme_classic(base_size = 13) +
  theme(
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    legend.position = c(0.85, 0.21),
    legend.background = element_rect(fill = "white", colour = "black")
  ) +
  scale_x_continuous(limits = c(0, 20500), breaks = seq(0, 20000, by = 10000), expand = c(0, 0.01)) +
  scale_y_continuous(limits = c(0.5, 1), breaks = seq(0.5, 1, by = 0.05), expand = c(0.01, 0)) +
  ylab("B") +
  theme(axis.title.x = element_blank()) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) +
  xlab("Distance from 10 kb conserved element (bp)")

fig_f
```

```{r}
ggsave("/revision_results/figures/r_misspec.pdf", fig_r, device = "pdf", dpi = 200, height = 6 * (5.2/8), width = 5.2, units = "in")
ggsave("/revision_results/figures/g_misspec.pdf", fig_g, device = "pdf", dpi = 200, height = 6 * (5.2/8), width = 5.2, units = "in")
ggsave("/revision_results/figures/f_misspec.pdf", fig_f, device = "pdf", dpi = 200, height = 6 * (5.2/8), width = 5.2, units = "in")

```


